<<<<<<< HEAD
# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./testlogclass.h
SOURCES += ./main.cpp \
    ./testlogclass.cpp
FORMS += ./testlogclass.ui
RESOURCES += ./testlogclass.qrc
=======
# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./testlogclass.h
SOURCES += ./main.cpp \
    ./testlogclass.cpp
FORMS += ./testlogclass.ui
RESOURCES += ./testlogclass.qrc
>>>>>>> 5ef3cb03e52ada26243983be502cd5530165f195
